import Footer from "@/components/global/footer";
import Header from "@/components/global/header";
import Banner from "@/components/pages/sec-banner";
import ContactUs from "@/components/pages/sec-contact";
import Url from "@/components/pages/sec-url";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Swenfly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
        
      </Head>
      <main className="relative">
        <Header />
        <section className="p-[10px] md:p-[24px]">
          <Banner />
          <Url />
          <ContactUs/>
          {/* <div className="space-50"></div> */}
        </section>
        <Footer />
      </main>
    </>
  );
}
